// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "MassEntityTypes.h"
#include "Core/EcoIds.h"
#include "AI/Policy/EcoPolicyContracts.h"
#include "EcoMassFragments.generated.h"

// -----------------------------------------------------------------------------
// Entity Fragments (Per-Agent unique mutable state)
// -----------------------------------------------------------------------------

/**
 * Identity fragment tracking unique agent and species membership.
 */
USTRUCT()
struct FEcoIdentityFragment : public FMassFragment
{
	GENERATED_BODY()

	/** Globally unique and persistent logical ID */
	UPROPERTY(EditAnywhere, Category = "Ecology|Mass")
	int64 StableAgentId = 0;

	/** Canonical species identifier */
	UPROPERTY(EditAnywhere, Category = "Ecology|Mass")
	FName SpeciesId = NAME_None;

	/** Compact hot-path runtime species index */
	UPROPERTY(VisibleAnywhere, Transient, Category = "Ecology|Mass")
	int32 SpeciesRuntimeIndex = INDEX_NONE_ECO;
};

/**
 * Vitals fragment managing health and energetic reserves.
 */
USTRUCT()
struct FEcoVitalsFragment : public FMassFragment
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, Category = "Ecology|Mass", meta = (ClampMin = "0.0"))
	float HP = 100.0f;

	UPROPERTY(EditAnywhere, Category = "Ecology|Mass", meta = (ClampMin = "0.0"))
	float MaxHP = 100.0f;

	UPROPERTY(EditAnywhere, Category = "Ecology|Mass", meta = (ClampMin = "0.0"))
	float Energy = 100.0f;

	UPROPERTY(EditAnywhere, Category = "Ecology|Mass", meta = (ClampMin = "0.0"))
	float MaxEnergy = 100.0f;
};

/**
 * Regional placement fragment tracking current habitat membership.
 */
USTRUCT()
struct FEcoRegionFragment : public FMassFragment
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, Category = "Ecology|Mass")
	FName CurrentRegionId = NAME_None;

	UPROPERTY(VisibleAnywhere, Transient, Category = "Ecology|Mass")
	int32 CurrentRegionIndex = INDEX_NONE_ECO;
};

/**
 * Migration and long-range travel state fragment.
 */
USTRUCT()
struct FEcoTravelFragment : public FMassFragment
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, Category = "Ecology|Mass")
	FName TargetRegionId = NAME_None;

	UPROPERTY(VisibleAnywhere, Transient, Category = "Ecology|Mass")
	int32 TargetRegionIndex = INDEX_NONE_ECO;

	UPROPERTY(EditAnywhere, Category = "Ecology|Mass", meta = (ClampMin = "0.0", ClampMax = "1.0"))
	float TravelProgress = 0.0f;

	UPROPERTY(EditAnywhere, Category = "Ecology|Mass")
	bool bIsTraveling = false;
};

/**
 * Normalized 7-dim observation vector snapshot for policy inference.
 */
USTRUCT()
struct FEcoObservationFragment : public FMassFragment
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, Transient, Category = "Ecology|Mass")
	FEcoPolicyObservationV1 Observation;
};

/**
 * 4-dim behavior steering force multipliers generated by policy inference.
 * Stored per entity to prevent archetype explosion.
 */
USTRUCT()
struct FEcoPolicyOutputFragment : public FMassFragment
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, Transient, Category = "Ecology|Mass")
	FEcoPolicyActionV1 Action;
};

/**
 * Timing and step tracking for rate-limited policy evaluation.
 */
USTRUCT()
struct FEcoPolicyRuntimeFragment : public FMassFragment
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, Transient, Category = "Ecology|Mass")
	int32 LastPolicyStep = 0;

	UPROPERTY(VisibleAnywhere, Transient, Category = "Ecology|Mass")
	int32 NextPolicyStep = 0;

	UPROPERTY(VisibleAnywhere, Transient, Category = "Ecology|Mass")
	int32 ModelRevision = 0;
};

// -----------------------------------------------------------------------------
// Shared Fragments (Species-wide immutable / slow-changing configuration)
// -----------------------------------------------------------------------------

/**
 * Shared configuration shared by all agents of the same species.
 */
USTRUCT()
struct FEcoSpeciesSharedFragment : public FMassSharedFragment
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, Category = "Ecology|Species")
	float BaseMoveSpeed = 400.0f;

	UPROPERTY(EditAnywhere, Category = "Ecology|Species")
	float EnergyDecayRate = 1.0f; // per second

	UPROPERTY(EditAnywhere, Category = "Ecology|Species")
	float FoodConsumptionRate = 5.0f; // biomass consumed per forage

	UPROPERTY(EditAnywhere, Category = "Ecology|Species")
	float FoodEnergyGain = 10.0f; // energy gain per unit food

	UPROPERTY(EditAnywhere, Category = "Ecology|Species")
	float ViewDistance = 1500.0f;

	UPROPERTY(EditAnywhere, Category = "Ecology|Species")
	float FOV = 120.0f;

	UPROPERTY(EditAnywhere, Category = "Ecology|Species")
	float CoverSearchRadius = 3000.0f;

	UPROPERTY(EditAnywhere, Category = "Ecology|Species")
	float MigrationThreshold = 0.2f; // energy below this ratio triggers migration urge
};

// -----------------------------------------------------------------------------
// Mass Tags (Minimal persistent categorical state)
// -----------------------------------------------------------------------------

/** Tag present on all living logical agents */
USTRUCT()
struct FEcoAliveTag : public FMassTag
{
	GENERATED_BODY()
};

/** Tag present when agent is actively performing cross-region migration */
USTRUCT()
struct FEcoMigratingTag : public FMassTag
{
	GENERATED_BODY()
};
